### ISSUE TITLE
4.3.3 Learning Objectives not posted on Training Kit

### ISSUE THREAD

**Issue by lineality** [bloominstituteoftechnology/DS-Unit-4-Sprint-3-Deep-Learning#109]
Learning Objectives
At the end of the lecture you should be to:

Part 1: Describe the componenets of an autoencoder
Part 2: Train an autoencoder
Part 3: Apply an autoenocder to a basic information retrieval problem

No 4.3.3 learning objects on main or day page of Training Kit
https://learn.lambdaschool.com/ds/sprint/rec5inpL5t6W30CFH

**Comment by sokjc** [comment]
This is a duplicate of another issue, so I am closing.
